#!/bin/bash

# hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

#install zsh
echo 'install oh-my-zhs'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L http://install.ohmyz.sh | sh

#global gitigore
ln -s $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore

#global gitigore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

#symlink bash_profile
rm $HOME/.bash_profile
ln -s $HOME/.dotfiles/shell/.bash_profile $HOME/.bash_profile

#symlink yarnrc
rm $HOME/.yarnrc
ln -s $HOME/.dotfiles/shell/.yarnrc $HOME/.yarnrc

#symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

#symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc

#symlink yarn prefs
rm $HOME/.npmrc
ln -s $HOME/.dotfiles/shell/.yarnrc $HOME/.npmrc

rm -R $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

#fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
cd ~/.oh-my-zsh/themes/
git checkout d6a36b1 agnoster.zsh-theme

echo 'install composer'
echo '----------------'
cd ~/.dotfiles
curl -sS https://getcomposer.org/installer | php
echo 'move composer to /usr/local/bin/composer'
mv -f composer.phar /usr/local/bin/composer

#activate z
cd ~/.dotfiles/shell
chmod +x z.sh

echo 'install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo 'install git'
echo '------------'
brew install git

echo 'install wget'
echo '------------'
brew install wget --overwrite

echo 'install httpie'
echo '------------'
brew install httpie

echo 'install ncdu'
echo '------------'
brew install ncdu

echo 'install hub'
echo '-----------'
brew install hub

echo 'install ack'
echo '------------'
brew install ack

echo 'install doctl'
echo '-------------'
brew install doctl

echo 'install brew-cask'
echo '------------------'
brew tap caskroom/cask
brew install brew-cask
brew tap caskroom/versions

echo 'install httrack'
echo '-------------'
brew install httrack

echo 'install z'
echo '-------------'
brew install z

echo 'install some nice quicklook plugins'
echo '-----------------------------------'
brew cask install --force qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql webp-quicklook suspicious-package

echo 'install laravel envoy'
echo '---------------------'
composer global require "laravel/envoy=dev-master";

echo 'install php-cs-fixer'
echo '--------------------'
composer global require friendsofphp/php-cs-fixer

echo 'install laravel installer'
echo '--------------------'
composer global require "laravel/installer=dev-master";

echo 'install laravel installer'
echo '--------------------'
composer global require "laravel/installer=dev-master";

echo 'install lumen installer'
echo '--------------------'
composer global require "laravel/lumen-installer=dev-master";

echo 'install wp-cli'
echo '--------------------'
composer global require "wp-cli/wp-cli=dev-master";

echo 'install php_codesniffer'
echo '--------------------'
composer global require "squizlabs/php_codesniffer=dev-master";

echo 'install laravel valet'
echo '---------------------'
composer global require laravel/valet
valet install

echo 'install laravel valet'
echo '---------------------'
composer global require spatie/phpunit-watcher

echo 'install php'
echo '------------'
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
brew install php71
brew install php71-xdebug
sudo brew services start homebrew/php/php71
brew install homebrew/php/php71-mcrypt
brew install homebrew/php/php71-imagick

echo 'install redis'
echo '------------'
brew install redis
brew install --HEAD homebrew/php/php71-redis

echo 'install mysql'
echo '---------------'
brew install mysql
brew services start mysql

echo 'install ghostscript'
echo '-------------------'
brew install ghostscript

echo 'install yarn'
echo '------------'
brew install yarn

echo 'install gulp'
echo '------------'
npm install -g gulp

echo 'install svgo'
echo '------------'
npm install -g svgo

echo 'install system apps'
echo '------------'
brew cask install dropbox
brew cask install slack
brew cask install invisionsync
brew cask install skype
brew cask install sketch
brew cask install chrome-devtools
brew cask install google-chrome
brew cask install firefox
brew cask install opera
brew cask install mamp
brew cask install google-nik-collection
brew cask install alfred
brew cask install bartender
brew cask install iterm2
brew cask install tower
brew cask install google-adwords-editor
brew cask install google-hangouts
brew cask install google-web-designer
brew cask install google-backup-and-sync
brew cask install sublime-text-dev
brew cask install phpstorm
brew cask install coda
brew cask install transmit
brew cask install teamviewer
brew cask install moom
brew cask install querious
brew cask install sequel-pro
brew cask install spotify
brew cask install postman
brew cask install poedit
brew cask install xmind
brew cask install vlc
brew cask install whatsapp
brew cask install screaming-frog-seo-spider
brew cask install jbidwatcher
brew cask install jdownloader
brew cask install evernote
brew cask install docker-edge
brew cask install adobe-creative-cloud
brew cask install docker-toolbox
brew cask install calibre
brew cask install colorsnapper

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'all done'
echo 'Things to do to make the agnoster terminal theme work:'

#patch font contains right characters for promt
echo '1. install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf' 

#install solarized http://ethanschoonover.com/solarized
echo '2. install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. set some sensible os x defaults by running: $HOME/.dotfiles/osx/set-defaults.sh'
echo '2. make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
