#!/bin/bash
set -e

# hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# install zsh
echo 'install oh-my-zhs'
echo '-----------------'
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# Set zsh as default shell
ZSH_PATH=$(which zsh)
if ! grep -q "$ZSH_PATH" /etc/shells; then
  echo "Adding $ZSH_PATH to /etc/shells. You might be asked for your password."
  sudo sh -c "echo $ZSH_PATH >> /etc/shells"
fi
chsh -s "$ZSH_PATH"

git clone https://github.com/jessarcher/zsh-artisan.git $HOME/.oh-my-zsh/custom/plugins/artisan

# symlink bash_profile
ln -sf $HOME/.dotfiles/shell/.bash_profile $HOME/.bash_profile

# symlink profile
ln -sf $HOME/.dotfiles/shell/.bash_profile $HOME/.profile

# symlink zsh prefs
ln -sf $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# symlink vim prefs
ln -sf $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc

# vim config
ln -sf $HOME/.dotfiles/shell/.vim $HOME/.vim

echo 'Install homebrew'
echo '----------------'
if ! command -v brew &> /dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo 'install git'
echo '------------'
brew install git

# global git config
ln -sf $HOME/.dotfiles/shell/.gitconfig $HOME/.gitconfig

# global gitigore
ln -sf $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

echo 'install httrack'
echo '-------------'
brew install httrack

echo 'install z'
echo '-------------'
brew install z

echo 'Install ack'
echo '-----------'
brew install ack

# echo 'Install php'
# echo '-----------'
# PHP is managed by Herd, so we dont need to install it here.
# brew install php

echo 'Install node'
echo '-----------'
brew install node

echo 'Configure npm'
echo '-------------'
# Create a directory for global packages and tell npm where to store globally installed packages
mkdir -p "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"

echo 'Install zsh-autosuggestions'
echo '---------------------------'
brew install zsh-autosuggestions

echo 'install yarn'
echo '------------'
brew install yarn

echo 'install svgo'
echo '------------'
npm install -g svgo

echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick

echo 'Install composer'
echo '----------------'
brew install composer

# echo 'install valet'
# echo '------------'
# The .zshrc is configured for Herd, so we are not installing Valet.
# If you want to use Valet, uncomment these lines and remove the Herd config from .zshrc
# composer global require laravel/valet
# valet install
# cd ~/Sites
# valet park
# valet trust

echo 'install mailhog'
echo '------------'
brew install mailhog
brew services start mailhog
# If using Valet, you can proxy mailhog
# valet proxy mailhog.test http://127.0.0.1:8025

echo 'Install some nice quicklook plugins'
echo '-----------------------------------'
brew install --cask qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzip suspicious-package

echo 'Automate daily updates'
echo '------------------------'
cp com.user.daily-updates.plist.template com.user.daily-updates.plist
sed -i '' "s|/ABSOLUTE/PATH/TO/HOME|$HOME|g" com.user.daily-updates.plist
cp bin/daily-updates.sh.template bin/daily-updates.sh
sed -i '' "s|/ABSOLUTE/PATH/TO/HOME|$HOME|g" bin/daily-updates.sh
chmod +x bin/daily-updates.sh
mkdir -p ~/Library/LaunchAgents
cp com.user.daily-updates.plist ~/Library/LaunchAgents/
launchctl load -w ~/Library/LaunchAgents/com.user.daily-updates.plist


# echo 'install system apps'
# echo '------------'
# brew install --cask --force screaming-frog-seo-spider sketch alfred google-hangouts spotify anydesk google-web-designer sublime-text balenaetcher grammarly tableplus bartender iterm2 teamviewer calibre lingo the-unarchiver craftmanager macdown tower diffmerge mamp vlc docker moom whatsapp dropbox phpstorm xmind evernote poedit zeplin firefox postman

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Make sure dropbox is running first. If you have not backed up via Mackup yet, then run `mackup backup` to symlink preferences for a wide collection of apps to your dropbox. If you already had a backup via mackup run `mackup restore` You'\''ll find more info on Mackup here: https://github.com/lra/mackup.'
echo '2. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '3. Make a .dotfiles-custom/shell/.aliases for your personal commands'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
